version: "3"

services:
    nginx:
        image: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./config/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - gunicorn

    redis:
        image: redis
        restart: always
        command: redis-server
        expose:
            - "6379"

    gunicorn:
        build: 
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        command: bash -c "venv/bin/gunicorn --workers 4 --bind 0.0.0.0:8000 FireProject.wsgi:application"
        expose:
            - "8000"
        depends_on:
            - redis
        env_file:
            .env
        environment:
            SECRET_KEY: "${SECRET_KEY}"
            ACCESS_SECRET_KEY: "${ACCESS_SECRET_KEY}"
        
            DEBUG: "${DEBUG}"
          
            BROKER_URl: "redis://redis:6379/0"

            NAME_DB: "${NAME_DB}" 
            USER_DB: "${USER_DB}" 
            PASSWORD_DB: "${PASSWORD_DB}" 
            HOST_DB: "${HOST_DB}" 
            PORT_DB: "${POST_DB}"


